// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTU6z25hgn1s7rgLgZnZucfesB3Kr84-A',
    appId: '1:59724517764:android:9a49a7a8c9e360bd6f8dd1',
    messagingSenderId: '59724517764',
    projectId: 'task2-1e19e',
    storageBucket: 'task2-1e19e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVwoxzFHJ94lwWxBphJLokMx_D-h3JH5E',
    appId: '1:59724517764:ios:fb11120a4df6fdb66f8dd1',
    messagingSenderId: '59724517764',
    projectId: 'task2-1e19e',
    storageBucket: 'task2-1e19e.firebasestorage.app',
    androidClientId: '59724517764-a31eqpva96jtuuam6avlcjg0d121i628.apps.googleusercontent.com',
    iosClientId: '59724517764-v2au8h3e6jhvgq7r5aca53514tk9a82l.apps.googleusercontent.com',
    iosBundleId: 'com.example.task2',
  );

}